### ISSUE TITLE
PHP 7 deprecation errors

### ISSUE THREAD

**Issue by andreasnij** [klarna/php-xmlrpc#7]
Using this library with PHP 7 triggers several deprecation errors. Example:

```
Methods with the same name as their class will not be constructors in a future version of PHP; 
xmlrpc_client has a deprecated constructor
```

I have reported the issue to the phpxmlrpc project and they recommend updating to version 4.0.

**Comment by JoakimLofgren** [comment]
Fixed in v5.0.0
