### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by mladenilic** [klarna/php-xmlrpc#8]
With current file structure, this library is almost unusable in projects. Lets consider following example project structure:

```
|-- app/
  |-- app.php
|-- lib/
```

Project adheres to **PSR-0** standard, _lib/_ is added to include path, so including this library should be straightforward. Since classes in this library are not scoped under directory (_Klarna/Invoice/_ perhaps?), after adding it, project would look something like this:

```
|-- app/
  |-- app.php
|-- lib/
  |-- Klarna/
    |-- ...
  |-- Klarna.php
  |-- KlarnaAddr.php
  |-- ...
```

Which looks messy to say at least. If we consider using this library alongside _kco_php_ library (much better one btw, real joy working with it), that's when the things get out of hand:

```
|-- app/
  |-- app.php
|-- lib/
  |-- Klarna/
    |-- Checkout/
      |-- ...
    |-- Checkout.php
    |-- ArgumentNotSetException.php
    |-- ...
  |-- Klarna.php
  |-- KlarnaAddr.php
  |-- ...
```

Libraries get merged into one messy blob of files, making it so much harder to work with them. I would also like to add that this is not some hypothetical scenario, which is unlikely to happen. Project structure used in this example is oversimplified structure of popular e-commerce framework and using these two two libraries together is almost unavoidable.

As a solution, I see scoping this library under _Klarna/Invoice/_, as mentioned above. That would result in a following project structure:

```
|-- app/
  |-- app.php
|-- lib/
  |-- Klarna/
    |-- Checkout/
      |-- ...
    |-- Invoice/
      |-- ...
    |-- Checkout.php
```

Which looks much, much better. This would also require some class name changes, to keep the **PSR-0**, which would than in turn mean that next version would not be backward compatible. Is such a change realistic? If not, I'd like to hear suggestions, which approach should one take to be able to use this library?

**Comment by JoakimLofgren** [comment]
We are actually working on a more modern take on this SDK, which should address this and more.

**Comment by mladenilic** [comment]
I hope you don't mind me asking, but are you referring to _kco_rest_php_?

**Comment by JoakimLofgren** [comment]
No, no, for the actual XMLRPC SDK.

**Comment by mladenilic** [comment]
Sounds great. Thanks for answering. :+1: 

Any chance you know when could we expect first release?

**Comment by JoakimLofgren** [comment]
@mladenilic Hopefully v5.0.0 addresses your issue.
I'll close this issue.
